[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino

monitor_speed = 115200
upload_speed = 921600

lib_ldf_mode = deep+

lib_deps =
    sparkfun/SparkFun MAX3010x Pulse and Proximity Sensor Library@1.1.2
    mikalhart/TinyGPSPlus

build_unflags =
    -Werror
    -Werror=all

build_flags =
    -Wall
